export const USER_POST_REQUEST = 'USER_POST_REQUEST'
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS'
export const USER_POST_FAIL = 'USER_POST_FAIL'
export const USER_POST_RESET = "USER_POST_RESET"

export const POST_LIST_REQUEST = "POST_LIST_REQUEST"
export const POST_LIST_SUCESSS = "POST_LIST_SUCESSS"
export const POST_LIST_FAIL = "POST_LIST_FAIL"


export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCESSS = "POST_DELETE_SUCESSS"
export const POST_DELETE_FAIL = "POST_DELETE_FAIL"