export const USER_POST_REQUEST = 'USER_POST_REQUEST'
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS'
export const USER_POST_FAIL = 'USER_POST_FAIL'
export const USER_POST_RESET = "USER_POST_RESET"

export const POST_LIST_REQUEST = "POST_LIST_REQUEST"
export const POST_LIST_SUCESSS = "POST_LIST_SUCESSS"
export const POST_LIST_FAIL = "POST_LIST_FAIL"


export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCESSS = "POST_DELETE_SUCESSS"
export const POST_DELETE_FAIL = "POST_DELETE_FAIL"

export const USER_THEME_REQUEST = "USER_THEME_REQUEST"
export const USER_THEME_SUCCESS = "USER_THEME_SUCCESS"
export const USER_THEME_FAIL = "USER_THEME_FAIL"


export const CHOOSE_THEME_REQUEST = "CHOOSE_THEME_REQUEST"
export const CHOOSE_THEME_SUCCESS = "CHOOSE_THEME_SUCCESS"
export const CHOOSE_THEME_FAIL = "CHOOSE_THEME_FAIL"


export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"

